name = "tstUSDC4"
chain = "mainnet"
address = "0x66d53A249cDB124Bc388b0f2c7E30DaB56BCEF01"

[calibers.mainnet]
address = "0xAc9c5477Dd6f2e9D55D408Efe7dE826B8Cd30E67"
swapper = "0xe403614F41554fC0f7A3dD581878D0024Dc978E9"
rootfiles = "github:MakinaHQ/makina-test-integrations/machines/tstUSDC4/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
decimals = 6
name = "USD Coin"
symbol = "USDC"
